# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run pytest on Linux
  pytest-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          activate-environment: "freecad"

      # Installs CadQuery and pytest so that the test can be run
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          conda install conda-forge::freecad
          conda install -c cadquery -c conda-forge cadquery=master
          conda install -c anaconda pytest

      # Runs the tests
      - name: Run tests
        shell: bash --login {0}
        run: |
          pytest -v

  # Run pytest on MacOS
  pytest-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          activate-environment: "freecad"
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          conda install conda-forge::freecad
          conda install -c cadquery -c conda-forge cadquery=master
          conda install -c anaconda pytest
      - name: Run tests
        shell: bash --login {0}
        run: |
          pytest -v

  # Run pytest on Windows
  pytest-win:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          python-version: "3.10"
          activate-environment: "freecad"
      - name: Install CadQuery and pytest
        shell: pwsh
        run: |
          conda install conda-forge::freecad
          conda install -c cadquery -c conda-forge cadquery=master
          conda install -c anaconda pytest
      - name: Run tests
        shell: pwsh
        run: |
          pytest -v
